POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
  "title": "451 Forwarded: The Future of Web Development",
  "author": "Horea Tiganas",
  "url": "https://ht.com",
  "likes": 9
}